force-app/main/default/objects/Email_Distribution_List__c/Email_Distribution_List__c.object-meta.xml
<CustomObject>
    <description>Used for the default test code included in the LightningLdv package. This is the parent of an &quot;Email Recipient&quot; custom object, and has a field called &quot;Recipients__c&quot; which is a comma separated list of the &quot;Email__c&quot; values from the child Email Recipients.</description>
    <label>Email Distribution List</label>
    <nameField>
        <label>Email Distribution List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Distribution Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Recipient__c/Email_Recipient__c.object-meta.xml
<CustomObject>
    <description>Used in the test code for the LightningLdv package.</description>
    <label>Email Recipient</label>
    <nameField>
        <label>Email Recipient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Recipients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Recipient__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Used in the test code for the LightningLdv package</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Email_Recipient__c/fields/Email_Distribution_List__c.field-meta.xml
<CustomField>
    <fullName>Email_Distribution_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used in the test code for the LightningLdv package</description>
    <label>Email Distribution List</label>
    <referenceTo>Email_Distribution_List__c</referenceTo>
    <relationshipLabel>Email Recipients</relationshipLabel>
    <relationshipName>Email_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailRecipientTriggerTest.cls
@IsTest private class EmailRecipientTriggerTest {

    @TestSetup private static void commonSetup(){
        Email_Distribution_List__c ed1 = new Email_Distribution_List__c(name='Marketing Distribution List');
        Email_Distribution_List__c ed2 = new Email_Distribution_List__c(name='Sales Distribution List');
        list<Email_Distribution_List__c> emailDistributionLists = new list<Email_Distribution_List__c>{ed1,ed2};
        insert emailDistributionLists;

        list<Email_Recipient__c> emailRecipients = new list<Email_Recipient__c>();
        for(integer i = 1; i <= 3; i++){
            String marketingRecipientName = getRecipientName('Marketing',i);
            String salesRecipientName = getRecipientName('Sales',i);
            
            Email_Recipient__c er1 = new Email_Recipient__c (
                name=marketingRecipientName,
                Email_Distribution_List__c = ed1.Id,
                Email__c=getRecipientEmail(marketingRecipientName)
            );
            emailRecipients.add(er1);

            Email_Recipient__c er2 = new Email_Recipient__c (
                name=salesRecipientName,
                Email_Distribution_List__c = ed2.Id,
                Email__c=getRecipientEmail(salesRecipientName)
            );
            emailRecipients.add(er2);
        }
        insert emailRecipients;

        Integer edlCount = (Integer)[Select count(Id) countVal FROM Email_Distribution_List__c].get(0).get('countVal');
        System.assertEquals(edlCount,2);

        Integer marketingRecipientsCount = (Integer)[Select count(Id) countVal FROM Email_Recipient__c WHERE Email_Distribution_List__c = :ed1.Id].get(0).get('countVal');
        System.assertEquals(marketingRecipientsCount,3);

        Integer salesRecipientsCount = (Integer)[Select count(Id) countVal FROM Email_Recipient__c WHERE Email_Distribution_List__c = :ed2.Id].get(0).get('countVal');
        System.assertEquals(salesRecipientsCount,3);
    }

    private static String getRecipientName(String prefix, Integer i){
        return prefix + ' Recipient ' + String.valueOf(i);
    }

    private static String getRecipientEmail(String name){
        return name.replace(' ','') + '@test.com';
    }

    private static testMethod void testInserts(){
        System.assert(true); //stub for test method
    }
}