force-app/main/default/objects/Email_Distribution_List__c/Email_Distribution_List__c.object-meta.xml
<CustomObject>
    <description>Used for the default test code included in the LightningLdv package. This is the parent of an &quot;Email Recipient&quot; custom object, and has a field called &quot;Recipients__c&quot; which is a comma separated list of the &quot;Email__c&quot; values from the child Email Recipients.</description>
    <label>Email Distribution List</label>
    <nameField>
        <label>Email Distribution List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Distribution Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Distribution_List__c/fields/Recipients__c.field-meta.xml
<CustomField>
    <fullName>Recipients__c</fullName>
    <description>Comma separated list of emails which is populated in the test trigger for the LightningLdv package.</description>
    <label>Recipients</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Recipient__c/Email_Recipient__c.object-meta.xml
<CustomObject>
    <description>Used in the test code for the LightningLdv package.</description>
    <label>Email Recipient</label>
    <nameField>
        <label>Email Recipient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Recipients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Recipient__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Used in the test code for the LightningLdv package</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Email_Recipient__c/fields/Email_Distribution_List__c.field-meta.xml
<CustomField>
    <fullName>Email_Distribution_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used in the test code for the LightningLdv package</description>
    <label>Email Distribution List</label>
    <referenceTo>Email_Distribution_List__c</referenceTo>
    <relationshipLabel>Email Recipients</relationshipLabel>
    <relationshipName>Email_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Global_Trigger_Settings__c/Global_Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define trigger settings that apply to all Lightning LDV triggers, such as regular maintenance hours and ad hoc disabling of all triggers</description>
    <label>Global Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Global_Trigger_Settings__c/fields/Blackout_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Blackout_Period_End__c</fullName>
    <description>Defines the end of a blackout period, during which all LDV trigger processing is disabled except for that which is required to enable later batch processing of that data. The Date portion of this field is relevant, unlike the maintenance window fields.</description>
    <label>Blackout Period End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Global_Trigger_Settings__c/fields/Blackout_Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Blackout_Period_Start__c</fullName>
    <description>Defines the beginning of a blackout period, during which all LDV trigger processing is disabled except for that which is required to enable later batch processing of that data. The Date portion of this field is relevant, unlike the maintenance window fields.</description>
    <label>Blackout Period Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Global_Trigger_Settings__c/fields/Maintenance_Window_End__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Window_End__c</fullName>
    <description>Defines the end of the maintenance window, during which all LDV trigger processing is disabled except for that which is required to enable later batch processing of that data. The Date portion of this field is ignored.</description>
    <label>Maintenance Window End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Global_Trigger_Settings__c/fields/Maintenance_Window_Start__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Window_Start__c</fullName>
    <description>Defines the beginning of the maintenance window, during which all LDV trigger processing is disabled except for that which is required to enable later batch processing of that data. The Date portion of this field is ignored.</description>
    <label>Maintenance Window Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestHelper.cls
public class TestHelper {
    public static String MARKETING_LIST = 'Marketing Distribution List';
    public static String SALES_LIST = 'Sales Distribution List';

    public static Global_Trigger_Settings__c commonConfig(){
        Date maintenanceDay = Utilities.getCurrentDate();
        DateTime maintenanceStartDateTime = DateTime.newInstance(maintenanceDay, Time.newInstance(1, 0, 0, 0));
        DateTime maintenanceEndDateTime = DateTime.newInstance(maintenanceDay, Time.newInstance(4, 0, 0, 0));
        
        Date blackoutDay = Utilities.getCurrentDate();
        DateTime blackoutStartDateTime = DateTime.newInstance(blackoutDay, Time.newInstance(13, 0, 0, 0));
        DateTime blackoutEndDateTime = DateTime.newInstance(blackoutDay, Time.newInstance(15, 0, 0, 0));

        return getGlobalTriggerSettings(maintenanceStartDateTime, maintenanceEndDateTime, blackoutStartDateTime, blackoutEndDateTime);
    }


    public static Global_Trigger_Settings__c altMaintenanceConfig(){ //maintnenance period crosses from one day to the next
        Date maintenanceDay = Utilities.getCurrentDate();
        DateTime maintenanceStartDateTime = DateTime.newInstance(maintenanceDay, Time.newInstance(23, 0, 0, 0));
        DateTime maintenanceEndDateTime = DateTime.newInstance(maintenanceDay.addDays(1), Time.newInstance(2, 0, 0, 0));
        
        Date blackoutDay = Utilities.getCurrentDate();
        DateTime blackoutStartDateTime = DateTime.newInstance(blackoutDay, Time.newInstance(13, 0, 0, 0));
        DateTime blackoutEndDateTime = DateTime.newInstance(blackoutDay, Time.newInstance(15, 0, 0, 0));

        return getGlobalTriggerSettings(maintenanceStartDateTime, maintenanceEndDateTime, blackoutStartDateTime, blackoutEndDateTime);
    }
    

    public static Global_Trigger_Settings__c getGlobalTriggerSettings(
        DateTime maintenanceStartDateTime, DateTime maintenanceEndDateTime,
        DateTime blackoutStartDateTime, DateTime blackoutEndDateTime
    ) {
        Global_Trigger_Settings__c orgDefaults = Global_Trigger_Settings__c.getOrgDefaults();
        orgDefaults.Maintenance_Window_Start__c = maintenanceStartDateTime;
        orgDefaults.Maintenance_Window_End__c = maintenanceEndDateTime;
        orgDefaults.Blackout_Period_Start__c = blackoutStartDateTime;
        orgDefaults.Blackout_Period_End__c = blackoutEndDateTime;
        return orgDefaults;
    }


    public static void commonSetup(Global_Trigger_Settings__c orgDefaults){
        insert orgDefaults;

        Email_Distribution_List__c ed1 = new Email_Distribution_List__c(name=MARKETING_LIST);
        Email_Distribution_List__c ed2 = new Email_Distribution_List__c(name=SALES_LIST);
        list<Email_Distribution_List__c> emailDistributionLists = new list<Email_Distribution_List__c>{ed1,ed2};
        insert emailDistributionLists;

        list<Email_Recipient__c> emailRecipients = new list<Email_Recipient__c>();
        for(integer i = 1; i <= 3; i++){
            String marketingRecipientName = getRecipientName('Marketing',i);
            String salesRecipientName = getRecipientName('Sales',i);
            
            Email_Recipient__c er1 = new Email_Recipient__c (
                name=marketingRecipientName,
                Email_Distribution_List__c = ed1.Id,
                Email__c=getRecipientEmail(marketingRecipientName)
            );
            emailRecipients.add(er1);

            Email_Recipient__c er2 = new Email_Recipient__c (
                name=salesRecipientName,
                Email_Distribution_List__c = ed2.Id,
                Email__c=getRecipientEmail(salesRecipientName)
            );
            emailRecipients.add(er2);
        }
        insert emailRecipients;
    }


    public static String getRecipientName(String prefix, Integer i){
        return prefix + ' Recipient ' + String.valueOf(i);
    }


    public static String getRecipientEmail(String name){
        return name.replace(' ','') + '@test.com';
    }


    public static void validateTestSetup(){
        System.debug('Utilities.getCurrentDate(): ' + Utilities.getCurrentDate().format());
        System.debug('Utilities.getCurrentDateTime(): ' + Utilities.getCurrentDateTime().format());
        System.debug('Utilities.getMaintenanceWindowStart(): ' + Utilities.getMaintenanceWindowStart().format());
        System.debug('Utilities.getMaintenanceWindowEnd(): ' + Utilities.getMaintenanceWindowEnd().format());
        System.debug('Utilities.getSoftMaintnanceWindowEnd(): ' + Utilities.getSoftMaintnanceWindowEnd().format());


        Global_Trigger_Settings__c orgDefaults = Global_Trigger_Settings__c.getOrgDefaults();
        System.assert(orgDefaults != NULL, 'Global_Trigger_Settings__c org default should have been inserted');

        Integer edlCount = (Integer)[SELECT count(Id) countVal FROM Email_Distribution_List__c].get(0).get('countVal');
        System.assertEquals(edlCount,2);

        Integer marketingRecipientsCount = (Integer)[SELECT count(Id) countVal FROM Email_Recipient__c WHERE Email_Distribution_List__r.Name = :MARKETING_LIST].get(0).get('countVal');
        System.assertEquals(marketingRecipientsCount,3);

        Integer salesRecipientsCount = (Integer)[SELECT count(Id) countVal FROM Email_Recipient__c WHERE Email_Distribution_List__r.Name = :SALES_LIST].get(0).get('countVal');
        System.assertEquals(salesRecipientsCount,3);
    }


     public static void validateDistributionList(String edlName, set<String> expectedValues){
        Email_Distribution_List__c edl = [SELECT Recipients__c FROM Email_Distribution_List__c WHERE Name = :edlName].get(0);
        set<String> actualValues = new set<String>();
        if(edl.Recipients__c != null){
            actualValues.addAll(edl.Recipients__c.split(','));
        }
        String errorMsg = 'Unexpected Recipients__c value for ' + edlName + ': \"' + edl.Recipients__c + '\".';
        errorMsg += ' Expected value was \"' + String.join(new list<String>(expectedValues), ',') + '\".';
        System.assert(expectedValues.equals(actualValues), errorMsg);
    }
}